services:
#Servicios EKL para los logs.
#La ventaja es que despliegan y analizan fallas, salidas de los comandos, pesos de archivos, etc.
  elasticsearch:
    image: elasticsearch:8.6.0
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
    volumes:
      - ./data:/usr/share/elasticsearch/data
    logging:
      driver: syslog
      options:
        tag: docker-elasticsearch

  kibana:
    image: kibana:8.6.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        tag: docker-kibana

  logstash:
    image: logstash:8.6.0
    ports:
      - "5000:5000/udp"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        tag: docker-logstash

  apache:
    image: httpd
    ports:
      - "4431:80"
    logging:
      driver: syslog
      options:
        tag: docker-apache

  nginx:
    image: nginx
    ports:
      - "4432:80"
    logging:
      driver: syslog
      options:
        tag: docker-nginx

  db01:
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3316:3306
    logging:
      driver: syslog
      options:
        tag: docker-db01

  db02:
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3317:3306
    logging:
      driver: syslog
      options:
        tag: docker-db02